# we need run the test suites inside the docker container on Travis CI systems
sudo: required
services:
  - docker
before_install:
  - docker build -t fayosaadi/react-docker -f Dockerfile.dev .
script:
  - docker run fayosaadi/react-docker yarn test:ci
