# we need run the test suites inside if the docker container
sudo: required

services:
  - docker

before_install:
  - docker build -t fayosaadi/react-docker -f Dockerfile.dev .

script:
  - docker run fayosaadi/react-docker npm run test:ci -- --coverage
