# we need run the test suites inside the docker container on Travis CI systems
sudo: required
services:
  - docker
before_install:
  - docker -t fayosaadi/react-docker build -f dockerfile.dev .
script:
  - docker run fayosaadi/react-docker yarn test:ci
