# run the test suites inside the docker container on Travis CI systems
sudo: required
services:
  - docker

before_install:
  - docker build -t fayosaadi/react-docker -f Dockerfile.dev .

script:
  - docker run fayosaadi/react-docker yarn test:ci

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket: "elasticbeanstalk-us-east-2-786796795325"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
