FROM node:alpine

WORKDIR './app'

COPY package.json .

RUN npm install

# This is not necessary in development, because we can reference the local file system in the docker container
# using volumes
# COPY . .

CMD ["npm", "run", "start"]
