version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
        - "3000:3000"
    volumes:
      - /app/node_modules
      # This is essentially referencing/mapping the folder outside docker into app directory inside docker in order
      # to get hot reloading up and running
      - .:/app
